In [2]:
import numpy as np

In [3]:
minha_lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
minha_lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
np.array(minha_lista)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
minha_matriz = [[1,2,3,5,6],[7,8,9,10,11],[12,13,14,15,16]]

In [7]:
np.array(minha_matriz)
# retorna um array que converte a lista em matriz

array([[ 1,  2,  3,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [8]:
np.arange(0, 10, 2)
# retorna um array de inteiros divisíveis por 2

array([0, 2, 4, 6, 8])

In [9]:
np.linspace(0, 10,3)
# retorna um array em que 3 floats do range (0, 10) sejam igualmente espaçados

array([ 0.,  5., 10.])

In [10]:
np.random.rand(5, 2)
# retorna um array de floats aleatórios

array([[0.84696712, 0.51689463],
       [0.156329  , 0.59536805],
       [0.66453324, 0.07685102],
       [0.72011575, 0.58079136],
       [0.30993804, 0.11257576]])

In [17]:
np.random.randn(4)
#retorna array de floats com média 0 e desvio padrão 1

array([1.60143071, 1.47517375, 0.75188567, 1.53330923])

In [30]:
jogo1= np.random.randint(1, 60, 6)
jogo2= np.random.randint(1, 60, 6)
jogo3= np.random.randint(1, 60, 6)
jogo1+jogo2+jogo3
# retorna 6 inteiros aleatórios entre 1 e 60

array([ 85,  87,  92,  58,  88, 101])

In [19]:
np.round(np.random.rand(6)*100, 0)

array([97., 28., 74., 45., 72., 75.])

In [20]:
arr = np.random.rand(25)

In [21]:
arr

array([0.4925168 , 0.04551361, 0.47740522, 0.36866472, 0.0996261 ,
       0.46214483, 0.12213338, 0.44218068, 0.67844503, 0.41337099,
       0.40266215, 0.81206628, 0.96863212, 0.56520865, 0.40222552,
       0.90464517, 0.97427383, 0.61319055, 0.17814106, 0.56918643,
       0.10238682, 0.37513427, 0.58610684, 0.31837865, 0.1187315 ])

In [22]:
arr.shape
#aqui arr é um vetor em R1 de 25 valores

(25,)

In [23]:
arr.reshape(5,5)

array([[0.4925168 , 0.04551361, 0.47740522, 0.36866472, 0.0996261 ],
       [0.46214483, 0.12213338, 0.44218068, 0.67844503, 0.41337099],
       [0.40266215, 0.81206628, 0.96863212, 0.56520865, 0.40222552],
       [0.90464517, 0.97427383, 0.61319055, 0.17814106, 0.56918643],
       [0.10238682, 0.37513427, 0.58610684, 0.31837865, 0.1187315 ]])

In [24]:
arr.shape
#Mesmo fazendo reshape a variável arr, continua sendo vetor de (25,0). Para que ocorra a mudança em arr
# é necessário declarar novamente a variável e altera-la para outro nome de variável, como arr2, por exemplo

(25,)

In [25]:
arr2 = arr.reshape(5,5)

In [26]:
arr2

array([[0.4925168 , 0.04551361, 0.47740522, 0.36866472, 0.0996261 ],
       [0.46214483, 0.12213338, 0.44218068, 0.67844503, 0.41337099],
       [0.40266215, 0.81206628, 0.96863212, 0.56520865, 0.40222552],
       [0.90464517, 0.97427383, 0.61319055, 0.17814106, 0.56918643],
       [0.10238682, 0.37513427, 0.58610684, 0.31837865, 0.1187315 ]])

In [27]:
arr2.shape
#agora sim houve mudança em arr para arr2 e a variável é uma matriz(5, 5)

(5, 5)

Fim da aula 20

In [28]:
import numpy as np
#sempre que for realizar a utilização de alguma biblioteca, importe-a antes

In [29]:
arr = np.arange(0, 30, 3)

In [30]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [31]:
#selecionar o valor 9 dentro do array
arr[3]

9

In [32]:
#selecionar os valores de 9 a 21 dentro do array
arr[3:8]

array([ 9, 12, 15, 18, 21])

In [33]:
#selecionar todos os elementos antes do 15
arr[:5]

array([ 0,  3,  6,  9, 12])

In [34]:
#selecionar todos os elementos depois do 6
arr[3:]

array([ 9, 12, 15, 18, 21, 24, 27])

In [96]:
#arrays bidimencionais
arr2 = np.random.arangerandint(50)

AttributeError: module 'numpy.random' has no attribute 'arangerandint'

In [130]:
arr3= np.random.randint(0,99,50).reshape(5,10)

In [131]:
arr3

array([[27, 80,  8,  0, 40, 11, 83, 60, 46, 52],
       [56, 42, 59, 26, 52, 83, 79, 79, 84, 93],
       [89, 12, 33, 29, 33, 40, 24, 41,  1, 53],
       [52, 38, 70, 58, 63, 20, 10,  6, 38, 85],
       [ 7, 45, 32, 26, 45, 27, 70, 20, 11, 98]])

In [143]:
arr3[2, 7]

41